---
- name: Query IPv4 address of container
  shell: curl -s --unix-socket /var/lib/lxd/unix.socket http:/1.0/containers/{{ name }}/state | jq -r '.metadata.network.eth0.addresses | map(select(.family == "inet")) | .[0].address'
  register: query_ipv4_address
  changed_when: False
  args:
    warn: no

- name: Set IPv4 address of container as fact
  set_fact:
    ipv4_address_{{ name }}: "{{ query_ipv4_address.stdout }}"
