---
- name: Create a started container
  lxd_container:
    name: "{{ item }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: centos/7/amd64
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  with_items:
    - pgsql1
    - pgsql2

- name: Get IPv4 addresses of containers
  include: get_ipv4_address_of_container.yml name={{ item }}
  with_items:
    - pgsql1
    - pgsql2

- name: Create new inventory file
  template: src=development.j2 dest=./development
