---
postgresql_download_dir: /usr/local/downloads
postgresql_repo_rpm_url: http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm
postgresql_repo_rpm_path: "{{ postgresql_download_dir }}/{{ postgresql_repo_rpm_url | basename }}"
postgresql_major_dot_minor_version: "9.5"
postgresql_major_minor_version: "{{ postgresql_major_dot_minor_version | replace('.', '') }}"
postgresql_postgres_home: /var/lib/pgsql
postgresql_data_dir: "{{ postgresql_postgres_home }}/{{ postgresql_major_dot_minor_version }}/data"
postgresql_archive_dir: "{{ postgresql_postgres_home }}/{{ postgresql_major_dot_minor_version }}/archive"
postgresql_backup_dir: "{{ postgresql_postgres_home }}/{{ postgresql_major_dot_minor_version }}/backups"
postgresql_prefix_dir: /usr/pgsql-{{ postgresql_major_dot_minor_version }}
postgresql_bin_dir: "{{ postgresql_prefix_dir }}/bin"
postgresql_setup_command_path: "{{ postgresql_bin_dir }}//postgresql{{ postgresql_major_minor_version }}-setup"
postgresql_log_dir: /var/log/postgresql
postgresql_pid_dir: /var/run/postgresql
postgresql_port: 5432
postgresql_replication_user: repl_user
postgresql_replication_password: "{{ development.secrets.postgresql_replication_password }}"
postgresql_postgres_ssh_private_key: "{{ development.secrets.postgresql_postgres_ssh_private_key }}"
postgresql_postgres_ssh_public_key: "{{ development.secrets.postgresql_postgres_ssh_public_key }}"
