#!/bin/sh
src="$1"
dest="$2"
logfile=/tmp/my_restore.log
echo "`date +%Y-%m-%dT%H:%M:%S` my_restore started. src=$src dest=$dest" >> $logfile
scp "$src" "$dest" >> $logfile 2>&1
ret=$?
echo "`date +%Y-%m-%dT%H:%M:%S` my_restore done. exit_code=$ret" >> $logfile
exit $ret
